name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FILE_NAME: "Tees-AiT-Addons"
  FILE_EXTENSION: ".zip"
  BRANCHES: "1.20.1"
  PACKAGE_NAME: "assets,data,pack.mcmeta,pack.png"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.TAG_NAME }}"
        release_name: "Tees AiT Addons ${{ env.TAG_NAME }}"
        draft: false
        prerelease: false
    - name: Generate a zip archive for each branch
      run: |
        for branch in $(echo $BRANCHES | tr "," "\\n"); do
          zip -r "$FILE_NAME-$branch$FILE_EXTENSION" $PACKAGE_NAME
        done
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: "$FILE_NAME-$branch$FILE_EXTENSION"
        path: "$FILE_NAME-$branch$FILE_EXTENSION"
    - name: Update release
      uses: actions/update-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.RELEASE_ID }}
        body: "Build description here"
